2024-06-24 10:17:05,087 INFO robot.py:1299 Robot: try to connection robot.
2024-06-24 10:17:05,087 INFO conn.py:281 CONN TYPE is rndis
2024-06-24 10:17:05,087 INFO conn.py:321 SdkConnection: request_connection, local addr ('192.168.42.3', 10379), remote_addr ('192.168.42.2', 20020), proxy addr ('192.168.42.2', 30030)
2024-06-24 10:17:05,087 WARNING conn.py:274 SdkConnection: switch_remote_route, exception:[WinError 10051] A socket operation was attempted to an unreachable network, Please Check Connections.
2024-06-24 10:17:05,088 WARNING conn.py:275 SdkConnection:Traceback (most recent call last):
  File "D:\Subject\Robot Ai\Robot first week\RoboMaster-SDK\venv\lib\site-packages\robomaster\conn.py", line 253, in switch_remote_route
    self._sock.sendto(buf, remote_addr)
OSError: [WinError 10051] A socket operation was attempted to an unreachable network

2024-06-24 10:17:05,088 ERROR robot.py:1353 Robot: Connection Failed, Please Check Hareware Connections!!! conn_type rndis, host ('192.168.42.3', 10379), target ('192.168.42.2', 20020).
2024-06-24 10:17:05,089 INFO robot.py:1305 Robot: initialized, try to use default Client.
2024-06-24 10:17:05,089 ERROR client.py:70 Client: __init__, create Connection, exception: module 'robomaster.config' has no attribute 'DEFAULT_CONN_PROTO'
2024-06-24 10:17:05,089 WARNING client.py:105 Client: initialize, no connections, init connections first.
2024-06-24 10:17:05,090 INFO dds.py:186 Subscriber: dispatcher_task is running...
2024-06-24 10:17:05,090 INFO uart.py:68 serial: dispatcher_task is running...
2024-06-24 10:17:05,090 ERROR client.py:153 Client: send_sync_msg, client recv_task is not running.
2024-06-24 10:17:05,090 WARNING robot.py:1453 Robot: enable_sdk error.
2024-06-24 10:17:05,090 ERROR client.py:153 Client: send_sync_msg, client recv_task is not running.
2024-06-24 10:17:05,090 WARNING robot.py:1523 Robot: reset dds node fail!
2024-06-24 10:17:05,090 ERROR client.py:153 Client: send_sync_msg, client recv_task is not running.
2024-06-24 10:17:05,090 WARNING robot.py:1509 Robot: enable_dds err.
2024-06-24 10:17:05,090 ERROR client.py:153 Client: send_sync_msg, client recv_task is not running.
2024-06-24 10:17:05,091 ERROR client.py:153 Client: send_sync_msg, client recv_task is not running.
2024-06-24 10:17:05,091 WARNING vision.py:260 Robot: enable vision failed.
